# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# <https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file>

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "hello-cache-app"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "maven"
    directory: "hello-on-app"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "maven"
    directory: "hello-off-app"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "maven"
    directory: "hello-cache-redis"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Asia/Shanghai"